#pragma once

#define CALLBACK __stdcall

#define SCREEN_WIDTH 1000
#define SCREEN_HEIGHT 700
#define OUTSCREEN_EDGE 20

#define INFO_LINE_NUMBER 1
#define TILE_COLUMN_NUMBER 20
#define TILE_LINE_NUMBER 10
#define TILE_SIZE SCREEN_WIDTH / TILE_COLUMN_NUMBER


#define TOWER_SIZE (TILE_SIZE) * 0.8f
#define BULLET_SIZE (TOWER_SIZE) * 0.2f
#define ENEMY_SIZE (TILE_SIZE) * 0.6f
#define CASTLE_SIZE (TILE_SIZE) * 1.2f

#define START_MONEY 1000u
#define COIN_ITEM_MONEY 100u
#define DIFFICULTY_INCREASE_FACTOR 1.8f

#define WEAK_ENEMY_GOLD 20u
#define STRONG_ENEMY_WAVE 4
#define STRONG_ENEMY_GOLD 40u
#define HEALER_ENEMY_WAVE 9
#define HEALER_ENEMY_GOLD 30u
#define BUILDER_ENEMY_WAVE 15
#define BUILDER_ENEMY_GOLD 50u
#define VERY_STRONG_ENEMY_GOLD 750u

#define STANDARD_COLOR 0xFF391D69
#define STANDARD_PRICE 250u
#define STANDARD_WAVE 1
#define SLOWING_COLOR 0xFF4DB3D4
#define SLOWING_PRICE 500u
#define SLOWING_WAVE 3
#define EXPLOSIVE_COLOR 0xFF822048
#define EXPLOSIVE_PRICE 750u
#define EXPLOSIVE_WAVE 6
#define GOLDEN_COLOR 0xFFFFFF00
#define GOLDEN_PRICE 200u
#define GOLDEN_MAX_MONEY 500u
#define GOLDEN_WAVE 2
#define UPGRADE_PRICE 750u
#define BUY_DELAY 15.f
